name: Jekyll site CI

on:
  push:
    branches: [ bunny ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '10'
        cache: 'npm'
    - run: npm install

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Remove HTML extension
      run: ./remove-html.sh

    - name: Deploy to BunnyCDN
      uses: ayeressian/bunnycdn-storage-deploy@master
      with:
        source: "_site"
        storageZoneName: "${{ secrets.BUNNY_CDN_STORAGE_ZONE }}"
        accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"

