name: Jekyll site CI

on:
  push:
    branches: [ bunny ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '10'
        cache: 'npm'
    - run: npm install

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Remove HTML extension
      run: ./remove-html.sh

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      working-directory: ./_site/
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
